[package]
name = "installdiff"
version = "0.1.0"
edition = "2021"

[dependencies]
unix_mode = "0.1.4"
libc = "0.2.158"
clap = { version = "4.5.16", features = ["derive"] }
memmap2 = "0.9.4"
sha2 = "0.10.8"
md5 = "0.7.0"
